export function getScoreColor(score: number): { bg: string; text: string; border: string; circleBg: string; scoreBarBg: string } {
  if (score >= 7) return {
    bg: 'bg-emerald-50 dark:bg-emerald-950/20',
    text: 'text-emerald-600 dark:text-emerald-400',
    border: 'border-emerald-100 dark:border-emerald-900/30',
    circleBg: 'bg-emerald-500/20 border-emerald-500/40',
    scoreBarBg: 'bg-emerald-500',
  };
  if (score >= 4) return {
    bg: 'bg-amber-50 dark:bg-amber-950/20',
    text: 'text-amber-600 dark:text-amber-400',
    border: 'border-amber-100 dark:border-amber-900/30',
    circleBg: 'bg-amber-500/20 border-amber-500/40',
    scoreBarBg: 'bg-amber-500',
  };
  return {
    bg: 'bg-red-50 dark:bg-red-950/20',
    text: 'text-red-600 dark:text-red-400',
    border: 'border-red-100 dark:border-red-900/30',
    circleBg: 'bg-red-500/20 border-red-500/40',
    scoreBarBg: 'bg-red-500',
  };
}

export function getScoreLabel(score: number, lang: 'en' | 'hi'): string {
  if (lang === 'hi') {
    if (score >= 8.5) return 'बेहतरीन विकल्प';
    if (score >= 7) return 'अच्छा विकल्प';
    if (score >= 4) return 'मध्यम';
    return 'कमजोर विकल्प';
  } else {
    if (score >= 8.5) return 'Excellent Choice';
    if (score >= 7) return 'Good Choice';
    if (score >= 4) return 'Moderate';
    return 'Poor Choice';
  }
}

export function getNutriScoreColor(grade: string): string {
  const colors: Record<string, string> = {
    A: 'bg-emerald-600 text-white',
    B: 'bg-emerald-500 text-white',
    C: 'bg-yellow-500 text-black',
    D: 'bg-orange-500 text-white',
    E: 'bg-red-500 text-white',
  };
  return colors[grade.toUpperCase()] || 'bg-slate-400 text-white';
}

export function getNovaGroupColor(group: number): string {
  if (group <= 1) return 'bg-emerald-500';
  if (group <= 2) return 'bg-amber-500';
  return 'bg-red-500';
}

export const ALL_ALLERGENS = [
  { id: '1', name: 'Peanuts', emoji: '🥜' },
  { id: '2', name: 'Dairy', emoji: '🥛' },
  { id: '3', name: 'Gluten', emoji: '🌾' },
  { id: '4', name: 'Soy', emoji: '🫘' },
  { id: '5', name: 'Eggs', emoji: '🥚' },
  { id: '6', name: 'Tree Nuts', emoji: '🌰' },
  { id: '7', name: 'Fish', emoji: '🐟' },
  { id: '8', name: 'Shellfish', emoji: '🦐' },
  { id: '9', name: 'Sesame', emoji: '🫘' },
  { id: '10', name: 'Mustard', emoji: '🟡' },
];

export const TRANSLATIONS = {
  en: {
    common: {
      appName: "ScanWise",
      tagline: "Know what you eat. Eat what's right.",
      home: "Home",
      search: "Search",
      scan: "Scan",
      saved: "Saved",
      profile: "Profile",
      seeAll: "See All",
      save: "Save",
      share: "Share",
      scanAgain: "Scan Again",
      back: "Back",
      cancel: "Cancel",
      loading: "Loading...",
      error: "Something went wrong",
      retry: "Try Again",
      unsave: "Unsave",
    },
    home: {
      greeting: "Good morning",
      greetingEmoji: "👋",
      title: "What are you eating today?",
      searchPlaceholder: "Search any food product...",
      scanTitle: "Scan Any Barcode",
      scanDesc: "Instantly check nutrition scores, allergens & get AI health insights for any food product.",
      scanBtn: "Scan Now",
      scans: "Scans",
      allergens: "Allergens",
      favorites: "Favorites",
      allergenAlertTitle: "Allergen Alert Active",
      allergenAlertDesc: "You have {count} allergens set. We'll flag products containing them.",
      allergenAlertAction: "Update Profile →",
      browseCategories: "Browse Categories",
      recentScans: "Recent Scans",
    },
    categories: {
      "beverages": "Beverages",
      "snacks": "Snacks",
      "dairy": "Dairy",
      "bakery": "Bakery",
      "canned": "Canned",
    },
    scanner: {
      title: "Scan Barcode",
      instruction: "Point camera at the barcode",
      manualTitle: "Enter Barcode Manually",
      manualDesc: "Type the number below the barcode",
      gallery: "Gallery",
      pasteCode: "Paste Code",
      voice: "Voice",
      recentlyScanned: "Recently Scanned",
    },
    product: {
      scanwiseScore: "ScanWise Score",
      excellent: "Excellent Choice",
      good: "Good Choice",
      moderate: "Moderate",
      poor: "Poor Choice",
      allergenWarning: "Allergen Warning",
      nutriScore: "Nutri-Score",
      novaGroup: "NOVA Group",
      nutritionFacts: "Nutrition Facts",
      per100ml: "per 100ml",
      per100g: "per 100g",
      calories: "Calories",
      totalFat: "Total Fat",
      carbs: "Carbs",
      sugars: "Sugars",
      protein: "Protein",
      fiber: "Fiber",
      aiInsight: "AI Health Insight",
      aiPowered: "Powered by Gemini",
      healthierAlt: "Healthier Alternatives",
    },
    search: {
      placeholder: "Search products...",
      filterAll: "All",
      filterGood: "Good Score",
      filterModerate: "Moderate",
      filterLow: "Low Score",
      filterGlutenFree: "Gluten-Free",
      results: "results for",
      sort: "Sort",
      sortScore: "Score ↓",
      recentSearches: "Recent Searches",
      trending: "Trending",
    },
    favorites: {
      title: "My Library",
      tabFavorites: "Favorites",
      tabHistory: "History",
      streakTitle: "Day Scan Streak!",
      streakDesc: "You're on fire! Keep scanning to unlock badges.",
    },
    auth: {
      signIn: "Sign In",
      signUp: "Sign Up",
      email: "Email",
      password: "Password",
      emailPlaceholder: "you@example.com",
      passwordPlaceholder: "Enter your password",
      forgotPassword: "Forgot password?",
      orContinueWith: "or continue with",
      google: "Google",
      facebook: "Facebook",
      noAccount: "Don't have an account?",
      hasAccount: "Already have an account?",
      createAccount: "Create Account",
      name: "Full Name",
      namePlaceholder: "Rahul Sharma",
      confirmPassword: "Confirm Password",
    },
    profile: {
      editProfile: "Edit Profile",
      changePassword: "Change Password",
      exportData: "Export Data",
      darkMode: "Dark Mode",
      darkModeDesc: "Switch to dark theme",
      language: "Language",
      languageDesc: "English",
      allergenAlerts: "Allergen Alerts",
      allergenAlertsDesc: "Get notified about allergens",
      myAllergens: "My Allergens",
      addMore: "+ Add More",
      rateApp: "Rate ScanWise",
      feedback: "Feedback & Support",
      privacy: "Privacy Policy",
      signOut: "Sign Out",
      joined: "Joined",
      india: "India",
    },
    settings: {
      preferences: "Preferences",
      account: "Account",
      about: "About",
    },
  },
  hi: {
    common: {
      appName: "ScanWise",
      tagline: "जानिए आप क्या खा रहे हैं। सही खाएं।",
      home: "होम",
      search: "खोजें",
      scan: "स्कैन",
      saved: "सेव्ड",
      profile: "प्रोफ़ाइल",
      seeAll: "सभी देखें",
      save: "सेव करें",
      share: "शेयर करें",
      scanAgain: "फिर से स्कैन करें",
      back: "वापस",
      cancel: "रद्द करें",
      loading: "लोड हो रहा है...",
      error: "कुछ गलत हो गया",
      retry: "फिर से कोशिश करें",
      unsave: "अनसेव करें",
    },
    home: {
      greeting: "शुभ प्रभात",
      greetingEmoji: "👋",
      title: "आज आप क्या खा रहे हैं?",
      searchPlaceholder: "कोई भी खाद्य उत्पाद खोजें...",
      scanTitle: "कोई भी बारकोड स्कैन करें",
      scanDesc: "किसी भी खाद्य उत्पाद के लिए पोषण स्कोर, एलर्जी चेक और AI स्वास्थ्य जानकारी तुरंत प्राप्त करें।",
      scanBtn: "अभी स्कैन करें",
      scans: "स्कैन",
      allergens: "एलर्जी",
      favorites: "पसंदीदा",
      allergenAlertTitle: "एलर्जी अलर्ट सक्रिय",
      allergenAlertDesc: "आपकी {count} एलर्जी सेट है। हम उत्पादों में उनकी जांच करेंगे।",
      allergenAlertAction: "प्रोफ़ाइल अपडेट करें →",
      browseCategories: "श्रेणियां ब्राउज़ करें",
      recentScans: "हाल के स्कैन",
    },
    categories: {
      "beverages": "पेय पदार्थ",
      "snacks": "स्नैक्स",
      "dairy": "डेयरी",
      "bakery": "बेकरी",
      "canned": "कैन्ड",
    },
    scanner: {
      title: "बारकोड स्कैन करें",
      instruction: "कैमरे को बारकोड पर लगाएं",
      manualTitle: "बारकोड मैन्युअल दर्ज करें",
      manualDesc: "बारकोड के नीचे का नंबर टाइप करें",
      gallery: "गैलरी",
      pasteCode: "कोड पेस्ट करें",
      voice: "आवाज़",
      recentlyScanned: "हाल ही में स्कैन किए गए",
    },
    product: {
      scanwiseScore: "ScanWise स्कोर",
      excellent: "बेहतरीन विकल्प",
      good: "अच्छा विकल्प",
      moderate: "मध्यम",
      poor: "कमजोर विकल्प",
      allergenWarning: "एलर्जी चेतावनी",
      nutriScore: "न्यूट्री-स्कोर",
      novaGroup: "NOVA ग्रुप",
      nutritionFacts: "पोषण तथ्य",
      per100ml: "प्रति 100ml",
      per100g: "प्रति 100g",
      calories: "कैलोरी",
      totalFat: "कुल वसा",
      carbs: "कार्ब्स",
      sugars: "शर्करा",
      protein: "प्रोटीन",
      fiber: "फाइबर",
      aiInsight: "AI स्वास्थ्य अंतर्दृष्टि",
      aiPowered: "Gemini द्वारा संचालित",
      healthierAlt: "स्वस्थ विकल्प",
    },
    search: {
      placeholder: "उत्पाद खोजें...",
      filterAll: "सभी",
      filterGood: "अच्छा स्कोर",
      filterModerate: "मध्यम",
      filterLow: "कम स्कोर",
      filterGlutenFree: "ग्लूटेन-मुक्त",
      results: "के लिए परिणाम",
      sort: "क्रम",
      sortScore: "स्कोर ↓",
      recentSearches: "हाल की खोजें",
      trending: "ट्रेंडिंग",
    },
    favorites: {
      title: "मेरी लाइब्रेरी",
      tabFavorites: "पसंदीदा",
      tabHistory: "इतिहास",
      streakTitle: "दिन स्कैन स्ट्रीक!",
      streakDesc: "आप आग पर हैं! बैज अनलॉक करने के लिए स्कैन करते रहें।",
    },
    auth: {
      signIn: "साइन इन करें",
      signUp: "साइन अप करें",
      email: "ईमेल",
      password: "पासवर्ड",
      emailPlaceholder: "you@example.com",
      passwordPlaceholder: "अपना पासवर्ड दर्ज करें",
      forgotPassword: "पासवर्ड भूल गए?",
      orContinueWith: "या इससे जारी रखें",
      google: "Google",
      facebook: "Facebook",
      noAccount: "खाता नहीं है?",
      hasAccount: "पहले से खाता है?",
      createAccount: "खाता बनाएं",
      name: "पूरा नाम",
      namePlaceholder: "राहुल शर्मा",
      confirmPassword: "पासवर्ड की पुष्टि करें",
    },
    profile: {
      editProfile: "प्रोफ़ाइल संपादित करें",
      changePassword: "पासवर्ड बदलें",
      exportData: "डेटा एक्सपोर्ट करें",
      darkMode: "डार्क मोड",
      darkModeDesc: "डार्क थीम पर स्विच करें",
      language: "भाषा",
      languageDesc: "हिंदी",
      allergenAlerts: "एलर्जी अलर्ट",
      allergenAlertsDesc: "एलर्जी के बारे में सूचित करें",
      myAllergens: "मेरी एलर्जी",
      addMore: "+ और जोड़ें",
      rateApp: "ScanWise को रेट करें",
      feedback: "फीडबैक और सहायता",
      privacy: "गोपनीयता नीति",
      signOut: "साइन आउट",
      joined: "शामिल हुए",
      india: "भारत",
    },
    settings: {
      preferences: "प्राथमिकताएं",
      account: "खाता",
      about: "बारे में",
    },
  },
};
